#!/usr/bin/env python3
# PYTHON_ARGCOMPLETE_OK

from argparse import ArgumentDefaultsHelpFormatter, ArgumentParser

import argcomplete

from contxt.cli_bare.parsers import (AssetsParser, AuthParser, BusParser,
                                     ContxtParser, EmsParser, IotParser)

# Setup main parser
parser = ArgumentParser(description="Contxt CLI", formatter_class=ArgumentDefaultsHelpFormatter)
subparsers = parser.add_subparsers(title="subcommands", dest="command")

# Setup all subparsers
parsers = {
    'auth': AuthParser(subparsers),
    'iot': IotParser(subparsers),
    'ems': EmsParser(subparsers),
    'assets': AssetsParser(subparsers),
    'contxt': ContxtParser(subparsers),
    'bus': BusParser(subparsers)
}

# Setup tab autocompletion
argcomplete.autocomplete(parser)

# Parse args
args = parser.parse_args()

# Launch the command
if args.command:
    # Create auth
    from contxt.utils.auth import CLIAuth
    auth = CLIAuth()
    # Parse
    parsers[args.command].parse(args, auth)
else:
    # Print all subparser usages
    for p in parsers.values():
        p.parser.print_usage()
