__title__ = "contxt-sdk"
__description__ = "Contxt SDK from ndustrial.io"
__url__ = "https://github.com/ndustrialio/contxt-sdk-python"
__version__ = "0.0.1b5"
__author__ = "ndustrial.io"
__author_email__ = "dev@ndustrial.io"
__license__ = "ISC"
