name: Security Alerts

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: reload/github-security-jira@v1.x
        env:
          GH_SECURITY_TOKEN: ${{ secrets.GITHUBORGSECURITYTOKEN }}
          JIRA_TOKEN: ${{ secrets.JIRAORGAPITOKEN }}
          JIRA_HOST: https://ndustrialio.atlassian.net
          JIRA_USER: josh@ndustrial.io
          JIRA_PROJECT: GITSEC
          JIRA_WATCHERS: chris@ndustrial.io,john@ndustrial.io
          JIRA_RESTRICTED_COMMENT_ROLE: Users
